-- BigChatBox Features/RandomText.lua — Preview text pool
-- Provides random WoW-themed text for the Designer/preview widgets.
-- Add more lines to this table to expand the pool

local BCB = BigChatBox
BCB.PreviewTexts = {
    "For the Horde, obviously",
    "Zug zug but make it stylish",
    "Need tank, healer, and snacks",
    "Pulling in 3... 2... oh no",
    "Who ninja looted my boots",
    "AFK bio brb dragon fight",
    "That sheep was not marked",
    "Fear pathing is not a plan",
    "Lag is my final boss",
    "I swear I kicked that cast",
    "Meet at stone, summon pls",
    "Grats on that gray drop",
    "This key will be chill right",
    "Mana break or we wipe",
    "Stop standing in fire",
    "Pet pulled, not me",
    "Oops wrong spec again",
    "Roll need on vibes",
    "Hero now or never",
    "I thought you had aggro",
    "Brb respeccing life choices",
    "That was a tactical wipe",
    "Pull big or go home",
    "Where is the flight master",
    "Who skipped the quest text",
    "Inv for world boss pls",
    "That crit healed my soul",
    "Mount up slowpokes",
    "I lagged I promise",
    "Do not touch the patrol",
    "One more pull trust me",
    "Ready check or chaos",
    "Trinket on cooldown sad",
    "Stop breaking my sheep",
    "That mob has hands",
    "Can I get a summon",
    "Loot council says no",
    "This is a learning run",
    "Wrong portal again",
    "Gold pls repair broke",
    "That was almost clean",
    "Why is it enraged",
    "Stack up not spread",
    "I need more haste",
    "Who pulled extra",
    "Fear the murloc army",
    "Not the bees",
    "Did someone say loot",
    "My UI is fine",
    "See you at graveyard",
    "RIGHT SIDE! HANDLE IT!",
    "LEEEEROY JEEEEENKINS!",
    "Looking for good guild.",
    "MARCO!?",
    "POLO!!",
    "Many Whelps! Handle It!",
    "I'M OUT OF MANA!",
    "Need Tank, Healer, DPS",
    "For the Horde! Again!",
    "Did Someone Say Loot?",
    "Pull Big or Go Home",
    "Stop Standing in Fire",
    "AFK in Stormwind",
    "Inv for World Boss Plz",
    "That Sheep Was Not Marked",
    "Lag Is My Final Boss",
    "Oops Wrong Spec... Again",
    "I Wiped, But Still Epic",
    "Gold Please, Repair Broke",
    "Fear the Murloc Army",
    "Not the Bees!",
    "My Pet Pulled, Not Me",
    "Ready Check or Chaos",
}

function BCB.GetRandomPreviewText()
    if not BCB.PreviewTexts or #BCB.PreviewTexts == 0 then return "Type something here..." end
    return BCB.PreviewTexts[math.random(1, #BCB.PreviewTexts)]
end
